sonar.projectKey=umbrella-back
sonar.projectName=umbrella back
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.node.maxspace=512
